chore(docs): document the error types and variants in the `errors` module
near/near-jsonrpc-client-rs pull request #84
Opened 2022-04-16 01:22 UTC by iTranscend

Tracking issue: <https://github.com/near/near-jsonrpc-client-rs/issues/51>

Documented the error types and variants in the `errors` module.

2022-04-17 00:04 UTC, miraclx requested changes
+1

2022-04-17 00:04 UTC, miraclx commented on src/errors.rs
> +    /// An error returned when the rpc server is unable to validation a client's request.
This is returned exclusively for Invalid RPC methods. Technically, we should never have this issue with the client (if you stay away from `methods::any`). Still worth documenting, nonetheless.

2022-04-17 00:04 UTC, miraclx commented on src/errors.rs
> +    /// An error returned when the server cannot process a request from an rpc client.
This is an RPC method call error. Like an error returned directly from the method you called.

2022-04-17 00:04 UTC, miraclx commented on src/errors.rs
> +    /// An error returned when the rpc server returns a response without context i.e. a response the client doesn't understand.
+1

understand / expect 🤷🏽

2022-04-17 00:04 UTC, miraclx commented on src/errors.rs
> +    /// Meta errors returned by the rpc server.
We should probably be explicit about the fact that these are unexpected status code errors.

2022-04-17 00:04 UTC, miraclx commented on src/errors.rs
> +/// Errors returned by the rpc client.
Potential errors, maybe?

2022-04-17 00:04 UTC, miraclx commented on src/errors.rs
> +    /// These errors are returned when there's a problem sending a request to an rpc server.
Sending / receiving.

This works https://github.com/near/near-jsonrpc-client-rs/pull/84/files#diff-6ff19a1ff611f3835b5a025663cf4dec901ed914626f78847414836439bd1a79R48

2022-04-17 00:04 UTC, miraclx commented on src/errors.rs
> +    /// These errors are returned whenerver there's a problem with the rpc server.
Problem not necessarily "with" the server. But at least, returned "from" the server.

2022-04-20 02:53 UTC, miraclx requested changes

2022-04-20 02:53 UTC, miraclx commented on src/errors.rs
> +    /// The RPC server returns an internal server error.
```suggestion
    /// The RPC server returned an internal server error.
```

2022-04-20 02:53 UTC, miraclx commented on src/errors.rs
> +    /// The RPC server returns a response without context i.e. a response the client doesn't expect.
ditto.

```suggestion
    /// The RPC server returned a response without context i.e. a response the client doesn't expect.
```

2022-04-20 03:50 UTC, miraclx requested changes

2022-04-20 03:50 UTC, miraclx commented on src/errors.rs
> +    /// An error returned when the rpc server is unable to validation a client's request.
Okay, so this isn't just for invalid RPC methods. But also for cases where the RPC method is unable to parse the provided arguments.

2022-04-20 03:55 UTC, miraclx commented on src/errors.rs
> +    /// An error returned when the rpc server is unable to validation a client's request.
Or if the payload sent to the server, while a valid JSON RPC message, isn't structured as a request.

The inverse of https://github.com/near/near-jsonrpc-client-rs/blob/091fb5385d0212716f343e0cbf7752ea1ce210c4/src/errors.rs#L34-L36

2022-04-20 22:30 UTC, iTranscend commented
Requested changes addressed ✅

2023-12-22 12:28 UTC, frol commented
I will merge all the doc PRs as is, and we will address any further issues in separate PRs going forward.

2023-12-22 12:28 UTC, merged